home/views.py
from flask import Blueprint, session, render_template

from user.models import User
from feed.models import Feed
from feed.forms import FeedPostForm

home_app = Blueprint('home_app', __name__)

@home_app.route('/')
def home():
    if session.get('username'):
        form = FeedPostForm()

        user = User.objects.filter(
            username=session.get('username')
        ).first()

        feed_messages = Feed.objects.filter(
            user=user
        ).order_by('-create_date')[:10]

        return render_template('home/feed_home.html',
                               user=user,
                               form=form,
                               feed_messages=feed_messages
                               )

    else:
        return render_template('home/home.html')

user/views.py
from flask import Blueprint, render_template, request, redirect, session, url_for, abort
import bcrypt
import uuid
import os
from werkzeug import secure_filename
from mongoengine import Q
from datetime import datetime, date

from user.models import User
from user.forms import RegisterForm, LoginForm, EditForm, ForgotForm, PasswordResetForm
from utilities.common import email
from settings import UPLOAD_FOLDER
from utilities.imaging import thumbnail_process
from utilities.maxxSec import maxx_encode
from relationship.models import Relationship
from user.decorators import login_required
from feed.forms import FeedPostForm
from feed.models import Message

user_app = Blueprint('user_app', __name__)

@user_app.route('/register', methods=('GET', 'POST'))
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        # salt = bcrypt.gensalt()
        # hashed_password = bcrypt.hashpw(form.password.data, salt)
        code = str(uuid.uuid4())
        password64 = maxx_encode(form.password.data)
        user = User(
            username=form.username.data,
            password=password64,
            email=form.email.data,
            first_name=form.first_name.data,
            last_name=form.last_name.data,
            change_configuration={
                "new_email": form.email.data.lower(),
                "confirmation_code": code
            }
        )

        # email the user
        body_html = render_template('mail/user/register.html', user=user)
        body_text = render_template('mail/user/register.txt', user=user)
        email(user.email, "Welcome to White History Week", body_html, body_text)

        user.save()
        return redirect(url_for('home_app.home'))
    return render_template('user/register.html', form=form)


@user_app.route('/login', methods=('GET', 'POST'))
def login():
    form = LoginForm()
    error = None
    if request.method == 'GET' and request.args.get('next'):
        session['next'] = request.args.get('next')
    if form.validate_on_submit():
        user = User.objects.filter(
            username=form.username.data
        ).first()
        if user:
            pw_in = form.password.data
            pw_check = maxx_encode(pw_in)
            if user.password == pw_check:
#            if bcrypt.hashpw(form.password.data, user.password) == user.password:
                session['username'] = form.username.data
                if 'next' in session:
                    next = session.get('next')
                    session.pop('next')
                    return redirect(next)
                else:
                    return redirect(url_for('home_app.home'))
#                    return "<h3 style='color:#CB4154'>Successful login</h3><h4 >Waiting to implement 'home_app.home'</h4>"
            else:
                user = None
        if not user:
            error = 'Incorrect credentials'
    return render_template('user/login.html', form=form, error=error)


@user_app.route('/logout')
def logout():
    if session.get('username'):
        session.pop('username')
    return redirect(url_for('user_app.login'))


@user_app.route('/<username>/friends/<int:friends_page_number>', endpoint='profile-friends-page')
@user_app.route('/<username>/friends', endpoint='profile-friends')
@user_app.route('/<username>')
def profile(username, friends_page_number=1):
    logged_user = None
    edit_profile = False
    rel = None
    friends_page = False
    user = User.objects.filter(username=username).first()

    if user:
        if session.get('username'):
            logged_user = User.objects.filter(username=session.get('username')).first()
            rel = Relationship.get_relationship(logged_user, user)

        if session.get('username') and user.username == session.get('username'):
            edit_profile = True

        # get friends
        friends = Relationship.objects.filter(
            from_user=user,
            rel_type=Relationship.FRIENDS,
            status=Relationship.APPROVED
        )
        friends_total = friends.count()

        if 'friends' in request.url:
            friends_page = True
            friends = friends.paginate(page=friends_page_number, per_page=3)
        else:
            friends = friends[:5]
        form = FeedPostForm()

        # get user messages
        profile_messages = Message.objects.filter(
            Q(from_user=user) | Q(to_user=user)).order_by('-create_date')[:10]

        return render_template('user/profile.html',
                               user=user,
                               logged_user=logged_user,
                               rel=rel,
                               edit_profile=edit_profile,
                               friends=friends,
                               friends_total=friends_total,
                               friends_page=friends_page,
                               form=form,
                               profile_messages=profile_messages,
                               images=None
                               )
    else:
        abort(404)


@user_app.route('/edit', methods=('GET', 'POST'))
@login_required
def edit():
    error = None
    message = None
    user = User.objects.filter(username=session.get('username')).first()
    if user:
        form = EditForm(obj=user)
        if form.validate_on_submit():
            # check if image
            image_ts = None
            if request.files.get('image'):
                filename = secure_filename(form.image.data.filename)
                file_path = os.path.join(UPLOAD_FOLDER, 'user', filename)
                form.image.data.save(file_path)
                image_ts = str(thumbnail_process(file_path, 'user', str(user.id)))
            if user.username != form.username.data.lower():
                if User.objects.filter(username=form.username.data.lower()).first():
                    error = "Username already exists"
                else:
                    session['username'] = form.username.data.lower()
                    form.username.data = form.username.data.lower()
            if user.email != form.email.data.lower():
                if User.objects.filter(email=form.email.data.lower()).first():
                    error = "Email already exists"
                else:
                    code = str(uuid.uuid4())

                    user.change_configuration = {
                        "new_email": form.email.data.lower(),
                        "confirmation_code": code
                    }
                    user.email_confirmed = False
                    form.email.data = user.email
                    message = "You will need to confirm the new email to complete this change"

                    # email the user
                    body_html = render_template('mail/user/change_email.html', user=user)
                    body_text = render_template('mail/user/change_email.txt', user=user)
                    email(user.change_configuration['new_email'], "Confirm your new email", body_html, body_text)

            if not error:
                form.populate_obj(user)
                if image_ts:
                    user.profile_image = image_ts
                user.save()
                if not message:
                    message = "Profile updated"

        return render_template("user/edit.html", form=form, error=error, message=message, user=user)
    else:
        abort(404)


@user_app.route('/confirm/<username>/<code>', methods=('GET', 'POST'))
def confirm(username, code):
    user = User.objects.filter(username=username).first()
    if user and user.change_configuration and user.change_configuration.get('confirmation_code'):
        if code == user.change_configuration.get('confirmation_code'):
            user.email = user.change_configuration.get('new_email')
            user.change_configuration = {}
            user.email_confirmed = True
            user.save()
            return render_template('user/email_confirmed.html')
    else:
        abort(404)


@user_app.route('/forgot', methods=('GET', 'POST'))
def forgot():
    error = None
    message = None
    form = ForgotForm()
    if form.validate_on_submit():
        user = User.objects.filter(email=form.email.data.lower()).first()
        if user:
            code = str(uuid.uuid4())
            user.change_configuration = {
                "password_reset_code": code
            }
            user.save()

            # email the user
            body_html = render_template('mail/user/password_reset.html', user=user)
            body_text = render_template('mail/user/password_reset.txt', user=user)
            email(user.email, "Password reset request", body_html, body_text)

        message = "You will receive a password reset email if we find that email in our system"
    return render_template('user/forgot.html', form=form, error=error, message=message)


@user_app.route('/password_reset/<username>/<code>', methods=('GET', 'POST'))
def password_reset(username, code):
    message = None
    require_current = None

    form = PasswordResetForm()

    user = User.objects.filter(username=username).first()
    if not user or code != user.change_configuration.get('password_reset_code'):
        abort(404)

    if request.method == 'POST':
        del form.current_password
        if form.validate_on_submit():
            pw_in = form.password.data
            hashed_password = maxx_encode(pw_in)
            user.password = hashed_password
            # salt = bcrypt.gensalt()
            # hashed_password = bcrypt.hashpw(form.password.data, salt)
            # user.password = hashed_password
            user.change_configuration = {}
            user.save()

            if session.get('username'):
                session.pop('username')
            return redirect(url_for('user_app.password_reset_complete'))

    return render_template('user/password_reset.html',
                           form=form,
                           message=message,

templates/_formhelpers.html
{% macro render_field(field) %}

<div class="form-group">
  {{ field.label }}
  {{ field(**kwargs)|safe }}

  {% if field.errors%}
    <ul class="text-danger">
      {% for e in field.errors %}
      <li>{{ e }}</li>
      {% endfor %}
    </ul>
  {% endif %}
</div>

{% endmacro %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>White History Week</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet">
   <link href="https://fonts.googleapis.com/css2?family=Economica:wght@700&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/8f2c96ee81.js" crossorigin="anonymous"></script>
       <link href="{{ url_for('static', filename='css/base.css') }}" rel="stylesheet">
    {% block header %}{% endblock %}

  </head>
  <body>

    <div class="container">
         <a  href="{{ url_for('home_app.home') }}">
                <img src="{{ url_for('static', filename='images/mountains.jpeg')}}"  height="125" width="500" alt="whw logo">
            </a>
            <h1 class='headcap'  style="font-family: 'Economica', sans-serif;">
                <img src="{{ url_for('static', filename='assets/spacer.svg')}}"  height="15" width="15" alt="spacer">
                White History Week
            </h1>




    {% block content %}


    {% endblock %}
      <div class="col-md-offset-3 col-md-6">
        <hr />
        <footer>
          &copy; copyright 2020 White History Week
        </footer>
      </div>

    </div>

 <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    {% block end_body_js %}{% endblock %}

  </body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
{#          <div class="navbar-header">#}
{#            <a class="navbar-brand" href="{{ url_for('home_app.home') }}">#}
{#           <img src="{{ url_for('static', filename='images/mountains.jpg')}}" alt="whw logo" width="82" height="20"  >#}
{#            </a>#}
{#      </div>#}

    <div class="collapse navbar-collapse" >

    <ul class="nav navbar-nav">
{#     {% if session.username %}#}
{#      <li class="nav-item active">#}
{#        <a class="nav-link" href="#">{{ session.username }} <span class="sr-only">(current)</span></a>#}
{#      </li>#}
{#       {% else %}#}
{#      <li class="nav-item active">#}
{#        <a class="nav-link" href="#">Un-user</a>#}
{#      </li>#}
{#        {% endif %}#}

    {% if session.username %}

      <li class="nav-item dropdown active">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {{  session.username }}
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{{ url_for('user_app.profile',username=session.username) }}">View profile</a>
          <a class="dropdown-item" href="{{ url_for('user_app.edit') }}">Edit profile</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{{ url_for ('user_app.change_password') }}">Change password</a>
        </div>
      </li>
    {% endif %}

  {% if session.username %}
    <li class="active">
        <a href="{{ url_for('user_app.logout') }}" class="nav-link">Logout</a>
    </li>
    {% else %}
    <li class="active">
        <a href="{{ url_for('user_app.login') }}" class="nav-link">Login</a>
        <a href="{{ url_for('user_app.register') }}" class="nav-link">Register</a>
    </li>
    {% endif %}
{#      <li class="nav-item active">#}
{#        <a class="nav-link disabled" href="#">Disabled</a>#}
{#      </li>#}
    </ul>
</div>
</nav>